export const BATTLE = {
    PLAYER_ONE_NAME: 'BATTLE.PLAYER_ONE_NAME',
    PLAYER_TWO_NAME: 'BATTLE.PLAYER_TWO_NAME',
    MAKE_BATTLE_LOADING: 'BATTLE.MAKE_BATTLE_LOADING',
    MAKE_BATTLE_SUCCESS: 'BATTLE.MAKE_BATTLE_SUCCESS',
    MAKE_BATTLE_FAILURE: 'BATTLE.MAKE_BATTLE_FAILURE',
}