export const POPULAR = {
    SET_SELECTED_LANGUAGE: 'POPULAR.SET_SELECTED_LANGUAGE',
    GET_REPOS_LOADING: 'POPULAR.GET_REPOS_LOADING',
    GET_REPOS_SUCCESS: 'POPULAR.GET_REPOS_SUCCESS',
    GET_REPOS_FAILURE : 'POPULAR.GET_REPOS_FAILURE',
}